# test whether the degree distribution of interaction and co-occurrence networks can be detected 

library(poweRlaw)
library(dplyr)
library(gridExtra)
library(ggplot2)
# https://cran.r-project.org/web/packages/poweRlaw/vignettes/c_comparing_distributions.pdf
# https://cran.r-project.org/web/packages/poweRlaw/vignettes/d_jss_paper.pdf

# Files used here are generated by process_data_degSeq.py
args <- commandArgs(trailingOnly = TRUE)

cutoffalpha <- 0.01 # 0.05, 0.1, 0.15, 0.2
# nSpec <- 100  # 100 or 1000
folderName <- "./degree_sequences_np/"

fmax <- as.numeric(args[1]) # 0.3333 0.2 0.1
pPos <- as.numeric(args[2]) # 0.5
nSpec <- as.numeric(args[3])

# Initialize empty DataFrame with column names
df <- data.frame(
  degDistType = character(),
  iteration = integer(),
  p_gof_cooc = numeric(),
  R_exp_cooc = numeric(),
  p_exp_cooc = numeric(),
  R_logn_cooc = numeric(),
  p_logn_cooc = numeric(),
  R_pois_cooc = numeric(),
  p_pois_cooc = numeric(),
  p_gof_inter = numeric(),
  R_exp_inter = numeric(),
  p_exp_inter = numeric(),
  R_logn_inter = numeric(),
  p_logn_inter = numeric(),
  R_pois_inter = numeric(),
  p_pois_inter = numeric(),
  cooc_alpha = numeric(),
  cooc_xmin = numeric(),
  inter_alpha = numeric(),
  inter_xmin = numeric(),
  concluded_cooc = character(),
  concluded_inter = character(),
  stringsAsFactors = FALSE
)

# List to store plot objects
plot_list <- list()

for (trueType in c("power", "exp", "rand")) {
  for (i in 0:9) {
    # print(trueType)
    # print(i)
    filenameCooc <- paste0(folderName, "cooc/cooc_nodeDegree", 
                          nSpec, "_", "Fmax", fmax, "_pPos", pPos, "_", trueType, "_cutoffalpha", cutoffalpha, "_", i, ".csv")
    filenameInter <- paste0(folderName, "inter/inter_nodeDegree", 
                          nSpec, "_", "Fmax", fmax, "_pPos", pPos, "_", trueType, "_", i, ".csv")
    
    cooc_df <- read.csv(filenameCooc, header = TRUE)
    inter_df <- read.csv(filenameInter, header = TRUE)
    
    degreeDistCooc <- as.numeric(cooc_df[, 2])
    degreeDistInter <- as.numeric(inter_df[, 2])
    
    length(degreeDistCooc)
    # 1000 for the current sets

    if (sum(degreeDistCooc == 0) > 0.1 * length(degreeDistCooc)) { # if more than 10% 0's
        warning(paste("More than 10% zeros for coocurrence network degree for", trueType, "i=", i))
    } 
    degreeDistCooc <- round(degreeDistCooc[degreeDistCooc != 0])
    
    if (sum(degreeDistInter == 0) > 0.1 * length(degreeDistInter)) { # if more than 10% 0's
        warning(paste("More than 10% zeros for interaction network degree for", trueType, "i=", i))
    } 
    degreeDistInter <- round(degreeDistInter[degreeDistInter != 0])
    
    # fit power law model for coocurrence
    powLaw_cooc <- displ$new(degreeDistCooc)
    est_cooc <- estimate_xmin(powLaw_cooc)
    powLaw_cooc$setXmin(est_cooc) # this sets both parameters

    # fit alternative models for coocurrence - same xmin as power law
    exp_cooc <- disexp$new(degreeDistCooc)
    exp_cooc$setXmin(est_cooc$xmin)
    exp_cooc$setPars(estimate_pars(exp_cooc))

    logn_cooc <- dislnorm$new(degreeDistCooc)
    logn_cooc$setXmin(est_cooc$xmin)
    logn_cooc$setPars(estimate_pars(logn_cooc))

    pois_cooc <- dispois$new(degreeDistCooc)
    pois_cooc$setXmin(est_cooc$xmin)
    pois_cooc$setPars(estimate_pars(pois_cooc))

  if (i == 0) {
      # Save model objects for later plotting
      save_name_cooc <- paste0("./", folderName, "/models_", trueType, nSpec, "_fmax", fmax, "_pPos", pPos, "_cooc.RData")
      save(degreeDistCooc, powLaw_cooc, exp_cooc, logn_cooc, pois_cooc,
            file = save_name_cooc)
  }

    # Test 1: Goodness-of-fit test using bootstrap_p
    # H0: data is generated from a power law distribution
    # Returns a p-value: if p is large, power law is plausible; if p ≈ 0, reject power law
    bs_p_cooc <- bootstrap_p(powLaw_cooc, no_of_sims = 5000, threads = 10, seed = 1)
    p_gof_cooc <- bs_p_cooc$p

    # Test 2: Compare power law to alternative distributions using Vuong's test
    # For each comparison: positive R means power law is better, negative means alternative is better
    res_exp_cooc <- compare_distributions(powLaw_cooc, exp_cooc)
    R_exp_cooc <- res_exp_cooc$test_statistic
    p_exp_cooc <- res_exp_cooc$p_two_sided

    res_logn_cooc <- compare_distributions(powLaw_cooc, logn_cooc)
    R_logn_cooc <- res_logn_cooc$test_statistic
    p_logn_cooc <- res_logn_cooc$p_two_sided

    res_pois_cooc <- compare_distributions(powLaw_cooc, pois_cooc)
    R_pois_cooc <- res_pois_cooc$test_statistic
    p_pois_cooc <- res_pois_cooc$p_two_sided
    
    # fit power law model for interaction
    powLaw_inter <- displ$new(degreeDistInter)
    est_inter <- estimate_xmin(powLaw_inter)
    powLaw_inter$setXmin(est_inter) # this sets both parameters

    # fit alternative models for interaction - same xmin as power law
    exp_inter <- disexp$new(degreeDistInter)
    exp_inter$setXmin(est_inter$xmin)
    exp_inter$setPars(estimate_pars(exp_inter))

    logn_inter <- dislnorm$new(degreeDistInter)
    logn_inter$setXmin(est_inter$xmin)
    logn_inter$setPars(estimate_pars(logn_inter))

    pois_inter <- dispois$new(degreeDistInter)
    pois_inter$setXmin(est_inter$xmin)
    pois_inter$setPars(estimate_pars(pois_inter))

  if (i == 0) {
      # Save model objects for later plotting
      save_name_inter <- paste0(folderName, "models_", trueType, nSpec, "_fmax", fmax, "_pPos", pPos, "_inter.RData")
      save(degreeDistInter, powLaw_inter, exp_inter, logn_inter, pois_inter,
            file = save_name_inter)
  }

    # Test 1: Goodness-of-fit test using bootstrap_p
    # H0: data is generated from a power law distribution
    bs_p_inter <- bootstrap_p(powLaw_inter, no_of_sims = 5000, threads = 10, seed = 1)
    p_gof_inter <- bs_p_inter$p

    # Test 2: Compare power law to alternative distributions using Vuong's test
    # For each comparison: positive R means power law is better, negative means alternative is better
    res_exp_inter <- compare_distributions(powLaw_inter, exp_inter)
    R_exp_inter <- res_exp_inter$test_statistic
    p_exp_inter <- res_exp_inter$p_two_sided

    res_logn_inter <- compare_distributions(powLaw_inter, logn_inter)
    R_logn_inter <- res_logn_inter$test_statistic
    p_logn_inter <- res_logn_inter$p_two_sided

    res_pois_inter <- compare_distributions(powLaw_inter, pois_inter)
    R_pois_inter <- res_pois_inter$test_statistic
    p_pois_inter <- res_pois_inter$p_two_sided

    # Determine concluded distribution for cooccurrence
    # Set significance level
    alpha <- 0.05
    concluded_cooc <- "ns"
    if (!is.na(p_exp_cooc) && !is.na(p_logn_cooc) && !is.na(p_pois_cooc) &&
        p_exp_cooc < alpha && R_exp_cooc > 0 &&
        p_logn_cooc < alpha && R_logn_cooc > 0 &&
        p_pois_cooc < alpha && R_pois_cooc > 0) {
      concluded_cooc <- "power_law"
    } else if (!is.na(p_exp_cooc) && p_exp_cooc < alpha && R_exp_cooc < 0) {
      concluded_cooc <- "exponential"
    } else if (!is.na(p_logn_cooc) && p_logn_cooc < alpha && R_logn_cooc < 0) {
      concluded_cooc <- "lognormal"
    } else if (!is.na(p_pois_cooc) && p_pois_cooc < alpha && R_pois_cooc < 0) {
      concluded_cooc <- "poisson"
    }

    # Determine concluded distribution for interaction
    concluded_inter <- "ns"
    if (!is.na(p_exp_inter) && !is.na(p_logn_inter) && !is.na(p_pois_inter) &&
        p_exp_inter < alpha && R_exp_inter > 0 &&
        p_logn_inter < alpha && R_logn_inter > 0 &&
        p_pois_inter < alpha && R_pois_inter > 0) {
      concluded_inter <- "power_law"
    } else if (!is.na(p_exp_inter) && p_exp_inter < alpha && R_exp_inter < 0) {
      concluded_inter <- "exponential"
    } else if (!is.na(p_logn_inter) && p_logn_inter < alpha && R_logn_inter < 0) {
      concluded_inter <- "lognormal"
    } else if (!is.na(p_pois_inter) && p_pois_inter < alpha && R_pois_inter < 0) {
      concluded_inter <- "poisson"
    }

    # Add row to DataFrame
    new_row <- data.frame(
      degDistType = trueType,
      iteration = i,
      p_gof_cooc = p_gof_cooc,
      R_exp_cooc = R_exp_cooc,
      p_exp_cooc = p_exp_cooc,
      R_logn_cooc = R_logn_cooc,
      p_logn_cooc = p_logn_cooc,
      R_pois_cooc = R_pois_cooc,
      p_pois_cooc = p_pois_cooc,
      p_gof_inter = p_gof_inter,
      R_exp_inter = R_exp_inter,
      p_exp_inter = p_exp_inter,
      R_logn_inter = R_logn_inter,
      p_logn_inter = p_logn_inter,
      R_pois_inter = R_pois_inter,
      p_pois_inter = p_pois_inter,
      cooc_alpha = powLaw_cooc$getPars(),
      cooc_xmin = powLaw_cooc$getXmin(),
      inter_alpha = powLaw_inter$getPars(),
      inter_xmin = powLaw_inter$getXmin(),
      concluded_cooc = concluded_cooc,
      concluded_inter = concluded_inter,
      stringsAsFactors = FALSE
    )
    df <- rbind(df, new_row)
  }
}

# Create summary with proportion correct (similar to poweRlaw_test.r)
# Map true types to expected conclusions
df <- df %>%
  mutate(
    correct_cooc = case_when(
      degDistType == "power" & concluded_cooc == "power_law" ~ 1,
      degDistType == "exp" & concluded_cooc == "exponential" ~ 1,
      degDistType == "rand" & concluded_cooc == "poisson" ~ 1,
      TRUE ~ 0
    ),
    correct_inter = case_when(
      degDistType == "power" & concluded_inter == "power_law" ~ 1,
      degDistType == "exp" & concluded_inter == "exponential" ~ 1,
      degDistType == "rand" & concluded_inter == "poisson" ~ 1,
      TRUE ~ 0
    )
  )

# Summary table with numeric means (excluding character columns)
result <- df %>%
  group_by(degDistType) %>%
  summarise(across(where(is.numeric), mean))

write.csv(result, file = paste0(folderName, "summary_distributionCompare_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv"), row.names = FALSE)
write.csv(df, file = paste0(folderName, "distributionCompare_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv"), row.names = FALSE)

# Create detailed summary table with proportion correct (similar to poweRlaw_test.r)
summary_table <- df %>%
  group_by(degDistType) %>%
  summarise(
    n_replicates = n(),
    mean_R_exp_cooc = mean(R_exp_cooc, na.rm = TRUE),
    mean_p_exp_cooc = mean(p_exp_cooc, na.rm = TRUE),
    mean_R_logn_cooc = mean(R_logn_cooc, na.rm = TRUE),
    mean_p_logn_cooc = mean(p_logn_cooc, na.rm = TRUE),
    mean_R_pois_cooc = mean(R_pois_cooc, na.rm = TRUE),
    mean_p_pois_cooc = mean(p_pois_cooc, na.rm = TRUE),
    mean_R_exp_inter = mean(R_exp_inter, na.rm = TRUE),
    mean_p_exp_inter = mean(p_exp_inter, na.rm = TRUE),
    mean_R_logn_inter = mean(R_logn_inter, na.rm = TRUE),
    mean_p_logn_inter = mean(p_logn_inter, na.rm = TRUE),
    mean_R_pois_inter = mean(R_pois_inter, na.rm = TRUE),
    mean_p_pois_inter = mean(p_pois_inter, na.rm = TRUE),
    proportion_correct_cooc = mean(correct_cooc, na.rm = TRUE),
    proportion_correct_inter = mean(correct_inter, na.rm = TRUE),
    .groups = "drop"
  )

cat("\n\n=== SUMMARY TABLE WITH PROPORTION CORRECT ===\n\n")
print(summary_table)

# Save summary table
write.csv(summary_table, file = paste0(folderName, "summary_proportionCorrect_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv"), row.names = FALSE)
cat("\nSummary table saved to: ", folderName, "summary_proportionCorrect_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv\n")

# Create simplified summary (similar to poweRlaw_test.r simple_summary)
simple_summary <- summary_table %>%
  select(degDistType, n_replicates, proportion_correct_cooc, proportion_correct_inter)

cat("\n\n=== SIMPLIFIED SUMMARY: PROPORTION CORRECT BY DISTRIBUTION TYPE ===\n\n")
print(simple_summary, n = Inf)

# Save simple summary
write.csv(simple_summary, file = paste0(folderName, "simple_summary_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv"), row.names = FALSE)
cat("\nSimple summary saved to: ", paste0(folderName, "simple_summary_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".csv\n"))

##################################
### Create grid plot from saved data ###
##################################
library(poweRlaw)

fmax <- 0.2 # 0.3333 0.2 0.1
pPos <- 0.5 # 0.5
folderName <- "./degree_sequences_np/"

fig_foldername <- "/Users/fionacallahan/Documents/Nielsen_lab/TheoryCoOccur/figures/"
cutoffalpha <- 0.01
nSpec <- 100
if (nSpec == 100) {
  y_ticks <- c(0.01, 0.1, 1)  # consistent y-axis ticks for all plots
} else {
  y_ticks <- c(0.001, 0.01, 0.1, 1)  # consistent y-axis ticks for all plots
}

# Function to create a single plot
create_fit_plot <- function(dist_type, network_type) {
  # Load the saved model data
  load(paste0(folderName, "models_", dist_type, nSpec, "_fmax", fmax, "_pPos", pPos, "_", network_type, ".RData"))

  if (network_type == "cooc") {
    # plot cCDF of data
    plot(pois_cooc,
        ylab = "cCDF (log scale)",
        xlab = "Node degree (log scale)",
        ylim = c(min(y_ticks), 1),
        yaxt = "n",
        cex.lab = 1.2)
    axis(2, at = y_ticks, labels = y_ticks, las = 1)
    # plot fits
    lines(powLaw_cooc, col = "blue", lwd = 2)
    lines(pois_cooc, col = "red", lwd = 2)
    lines(logn_cooc, col = "black", lwd = 2)
    lines(exp_cooc, col = "orange", lwd = 2)
  } else {
    # plot cCDF of data
    plot(pois_inter,
        ylab = "cCDF (log scale)",
        xlab = "Node degree (log scale)",
        ylim = c(min(y_ticks), 1),
        yaxt = "n",
        cex.lab = 1.2)
    axis(2, at = y_ticks, labels = y_ticks, las = 1)
    lines(powLaw_inter, col = "blue", lwd = 2)
    lines(pois_inter, col = "red", lwd = 2)
    lines(logn_inter, col = "black", lwd = 2)
    lines(exp_inter, col = "orange", lwd = 2)
  }

  legend("bottomleft",
         legend = c("Power law", "Poisson", "Log-normal", "Exponential"),
         col = c("blue", "red", "black", "orange"),
         lty = 1, lwd = 2, cex = 1.2)
}

# Create high-quality grid plot
png(filename = paste0(fig_foldername, "plotFits_grid_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".png"),
    width = 5000, height = 4000, res = 600)

# Set up layout with margins for labels
# Outer margins: bottom, left, top, right
par(mfrow = c(2, 2),
    mar = c(4, 4, 2, 1),    # Individual plot margins
    oma = c(1, 6, 4, 1))    # Outer margins for labels

# Row 1: Power law
create_fit_plot("power", "inter")
create_fit_plot("power", "cooc")

# Row 2: Random (Binomial)
create_fit_plot("rand", "inter")
create_fit_plot("rand", "cooc")

# Add column labels at top
mtext("Interaction", side = 3, line = 0, outer = TRUE, at = 0.25, cex = 1.2, font = 2)
mtext("Co-occurrence", side = 3, line = 0, outer = TRUE, at = 0.75, cex = 1.2, font = 2)

# Add row labels on left side
mtext("Power law", side = 2, line = 2, outer = TRUE, at = 0.75, cex = 1.2, font = 2, las = 0)
mtext("Random (binomial)", side = 2, line = 2, outer = TRUE, at = 0.25, cex = 1.2, font = 2, las = 0)

dev.off()

cat("Grid plot saved to:", paste0(fig_foldername, "plotFits_grid_nspec", nSpec, "_cutoffalpha", cutoffalpha, "_fmax", fmax, "_pPos", pPos, ".png\n"))



##################################
######### goodness of fit ########
##################################

# cutoffalpha <- 0.01 # 0.05, 0.1, 0.15, 0.2
# nSpec <- 1000 # "" or "500" "1000"
# trueType <- "power"
# filenameCooc <- paste0(folderName, "/cooc/cooc_nodeDegree", 
#                         nSpec, "_", trueType, "_cutoffalpha", cutoffalpha, "_0.csv")
# filenameInter <- paste0(folderName, "inter/inter_nodeDegree", 
#                         nSpec, "_", trueType, "_0.csv")

# cooc_df <- read.csv(filenameCooc, header = TRUE, quote = "|")
# inter_df <- read.csv(filenameInter, header = TRUE, quote = "|")

# degreeDistCooc <- as.numeric(cooc_df[, 2])
# degreeDistInter <- as.numeric(inter_df[, 2])

# length(degreeDistCooc)
# # 1000 for the current sets

# if (sum(degreeDistCooc == 0) > 0.1 * length(degreeDistCooc)) { # if more than 10% 0's
#     warning(paste("More than 10% zeros for coocurrence network degree for", trueType, "i=", i))
# } 
# degreeDistCooc <- round(degreeDistCooc[degreeDistCooc != 0])

# if (sum(degreeDistInter == 0) > 0.1 * length(degreeDistInter)) { # if more than 10% 0's
#     warning(paste("More than 10% zeros for interaction network degree for", trueType, "i=", i))
# } 
# degreeDistInter <- round(degreeDistInter[degreeDistInter != 0])

# # fit four models to cooccurrence node degrees
# powLaw_cooc <- displ$new(degreeDistCooc)
# powLaw_cooc$setPars(estimate_pars(powLaw_cooc))

# exp_cooc <- disexp$new(degreeDistCooc)
# exp_cooc$setPars(estimate_pars(exp_cooc))

# logn_cooc <- dislnorm$new(degreeDistCooc)
# logn_cooc$setPars(estimate_pars(logn_cooc))

# pois_cooc <- dispois$new(degreeDistCooc)
# pois_cooc$setPars(estimate_pars(pois_cooc))


# # fit four models to interaction node degrees
# powLaw_inter <- displ$new(degreeDistInter)
# powLaw_inter$setPars(estimate_pars(powLaw_inter))

# exp_inter <- disexp$new(degreeDistInter)
# exp_inter$setPars(estimate_pars(exp_inter))

# logn_inter <- dislnorm$new(degreeDistInter)
# logn_inter$setPars(estimate_pars(logn_inter))

# pois_inter <- dispois$new(degreeDistInter)
# pois_inter$setPars(estimate_pars(pois_inter))

# # goodness of fit bootstrap -- KS stat -- lower is closer to true distribution -- if < 0.04 then it is significant for n=1000
# #interaction
# bs_pl_i <- bootstrap(powLaw_inter, no_of_sims = 5000, threads = 20, seed = 1)
# bs_pl_i$gof

# bs_exp_i <- bootstrap(exp_inter, no_of_sims = 5000, threads = 20, seed = 1)
# bs_exp_i$gof

# bs_ln_i <- bootstrap(logn_inter, no_of_sims = 5000, threads = 20, seed = 1)
# bs_ln_i$gof

# bs_pois_i <- bootstrap(pois_inter, no_of_sims = 5000, threads = 20, seed = 1)
# bs_pois_i$gof

# #coocurrence
# bs_pl_c <- bootstrap(powLaw_cooc, no_of_sims = 5000, threads = 20, seed = 1)
# bs_pl_c$gof

# bs_exp_c <- bootstrap(exp_cooc, no_of_sims = 5000, threads = 20, seed = 1)
# bs_exp_c$gof

# bs_ln_c <- bootstrap(logn_cooc, no_of_sims = 5000, threads = 20, seed = 1)
# bs_ln_c$gof

# bs_pois_c <- bootstrap(pois_cooc, no_of_sims = 5000, threads = 20, seed = 1)
# bs_pois_c$gof